A2_Recipe_App/src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout_success/', logout_success, name='logout_success')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A2_Recipe_App/src/recipes/urls.py
from django.urls import path
from .views import welcome, RecipeListView, RecipeDetailView


app_name = 'recipes'

urlpatterns = [
    path('', welcome, name='recipes_home'),
    path('list/', RecipeListView.as_view(), name='recipes_list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail')
]

A2_Recipe_App/src/recipes/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


difficulty_choices = (
    ('Easy', 'easy'),
    ('Medium', 'medium'),
    ('Intermediate,' 'intermediate'),
    ('Hard', 'hard'),
)

# Create your models here.
class Recipe (models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.IntegerField(help_text = 'In minutes')
    ingredients = models.CharField(max_length=350, help_text='Enter Ingredients seperated by Comma')
    difficulty = models.CharField( max_length=120, choices=difficulty_choices, default='Easy')
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')
    date_created = models.DateField(default=timezone.now)

    def get_absolute_url(self):
        return reverse ('recipes:detail', kwargs={'pk': self.pk})

    def difficulty(self):
        ingredients = self.ingredients.split(", ")
        if self.cooking_time < 10 and len(ingredients) < 4:
            return "Easy"
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            return "Medium"
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            return "Intermediate"
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            return "Hard"
        return "Unknown"

    def __str__(self):
       return str(self.name)


    def save(self, *args, **kwargs):
        self.difficulty()
        super().save(*args, **kwargs)

A2_Recipe_App/src/recipes/forms.py
from django import forms

CHART_CHOICES =(
    ('#1', 'Bar Chart'),
    ('#2', 'Pie Chart'),
    ('#3', 'Line Chart')
)

class RecipeSearchForm(forms.Form):
    recipe_name = forms.CharField(max_length=100)
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)

A2_Recipe_App/src/recipe_project/views.py
from django.shortcuts import render, redirect

#Django authentication libraries
from django.contrib.auth import authenticate, login, logout
#Django authentication form
from django.contrib.auth.forms import AuthenticationForm

#function to call login_view that takes request from user
def login_view(request):
    #initialize:
    #error_message to none
    error_message = None
    #form object with usernmae and password fields
    form = AuthenticationForm()

#When user hit login button post request is generated
    if request.method == 'POST':
        #reads data sent by form via post request
        form =AuthenticationForm(data=request.POST)

        #check if form is valid
        if form.is_valid():
            #read username
            username=form.cleaned_data.get('username')
            #read password
            password=form.cleaned_data.get('password')
            
            #Use DJango authenticate function to validate the user
            user=authenticate(username=username, password=password)
            if user is not None:
                #If user is authenticated, then use predefined function to login
                login(request,user)
                return redirect('recipes:recipes_list') #send user to desired page
            else:
                #In case of error, print error message
                error_message = 'oops... something went wrong'
    #Prepare data to send from view to template
    context ={
        'form': form, #End the form data
        'error_message': error_message #End error_message
    }
    #Load login page using context information
    return render(request, 'auth/login.html', context)



def logout_success(request):
    logout(request)
    return render(request, 'auth/success.html')

A2_Recipe_App/src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView 
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeSearchForm
from .utils import get_recipe_name_from_id, get_chart
import pandas as pd 
from django.urls import reverse
from django.db.models import Q 



# Create your views here.
def welcome(request):
    return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe

    def get(self, request):
        form= RecipeSearchForm()
        recipes = Recipe.objects.all()
        return render(request, 'recipes/recipes_list.html', {'form': form, 'recipes': recipes})

    
    def post(self, request):
        form = RecipeSearchForm(request.POST)
        recipes = Recipe.objects.all()
        chart = None

        if form.is_valid():
            recipe_name = form.cleaned_data.get('recipe_name')
            chart_type = form.cleaned_data.get('chart_type')

            qs = Recipe.objects.filter(Q(name__icontains=recipe_name) | Q(ingredients__icontains=recipe_name))
            if qs.exists():
                recipes = pd.DataFrame(qs.values())
                recipes['difficulty'] = recipes.apply(lambda row: get_recipe_name_from_id(row['id']).difficulty, axis=1)
                chart= get_chart(chart_type, recipes, labels=recipes['name'].values)
            else:
                recipes = pd.DataFrame()

        context = {
            'form': form,
            'recipes': recipes,
            'chart': chart
        }
        return render(request, 'recipes/recipes_list.html', context)

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/recipes_details.html"

A2_Recipe_App/src/recipes/templates/recipes/recipes_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/style.css' %}">
        <title>Recipe Details</title>
    </head>
    <body>
      <header>
        <h1>Details: {{object.name}}</h1>
      </header>
      <main>
        <div class="main-box">
          <div class="recipe-details"><b>Recipe: </b> {{object.name}} </div><br>
          <div class="recipe-details"><b>Cooking Time: </b> {{object.cooking_time}} </div><br>
          <div class="recipe-details"><b>Difficulty: </b> {{object.difficulty}} </div><br>
          <div class="recipe-details"><b>Ingredients: </b> {{object.ingredients}} </div><br>
          <img class="recipe-img" src="{{object.pic.url}}"/>
        </div>  
      </main>
        <br>
        <br>
          <a class="recipe-list-link" href="{% url 'recipes:recipes_list' %}">Back to Recipe List</a>
          <a class="recipe-list-link" href="{% url 'recipes:recipes_home' %}">Back to Home</a>
          <a class="logout-button" href ="{%url 'logout_success' %}">  Logout  </a>
        
      
    </body>
</html>

A2_Recipe_App/src/recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/style.css' %}">
    </head>    
    <title>
        Recipes App Home
    </title>
    
    <body>
        <header>
        
        <h1 class="header-text">
            Welcome to my Recipes App
        </h1>
        </header>
        <br>
        <img class="recipe-home-img" src="{% static 'recipes/images/recipe-one.jpg' %}" alt="recipe-image" width="600px" height="300" >
        <p>Take a look at our Recipes!</p>
        <a class="login-button" href="{% url 'login' %}"> Login </a>
        <a class="recipe-list-link" href="{% url 'recipes:recipes_list' %}" justify-content="center">View Recipe List</a>
    </body>
</html>

A2_Recipe_App/src/recipes/templates/recipes/recipes_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/style.css' %}">
        <title>Recipe Overview</title>
    </head>
    <body>
        <header>
            <h1>
                <p>Recipe List</p>
            </h1>
        </header>
        <main>
        <div class="main-box">
            <p>Search for an ingredient or recipe name:</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.recipe_name }}
                {{ form.chart_type }}
                <button type="submit">Search</button>
                <a href="{% url 'recipes:recipes_list' %}"><button type=button>Show All Recipes</button></a>    
            </form>
            {% if form.is_bound %}
            <p>You Searched for: {{form.recipe_name.value}}</p>
            {% if not recipes.empty %}
            <ul>
                {% for index, recipe in recipes.iterrows %}
                <li>
                    <h2><a href="{% url 'recipes:detail' pk=recipe.id %}">{{ recipe.name }}</a></h2>
                    <img src="/media/{{ recipe.pic }}" />
                </li>
                {% endfor %}
            </ul>
            <h1>Data Analytics</h1>
            <img class="chart-img" src="data:image/png;base64, {{chart|safe}}">
            {% else %}
                <h3>No data</h3>
                {% endif %}
        {% else %}
            <ul>
                {% for recipe in recipes %}
                <li>
                    <h2><a href="{% url 'recipes:detail' pk=recipe.id %}">{{ recipe.name }}</a></h2>
                    <img src="{{recipe.pic.url}}" height="auto" width="200px"/>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        </main>
        <a class="logout-button" href ="{%url 'logout_success' %}">  Logout  </a>
        <a class="home-link" href="{% url 'recipes:recipes_home' %}">Back to Home</a>
    </body>
</html>